name: $(date:yyyymmdd)$(rev:.rr) #20191209.00

trigger:      #every time there is push to master, trigger the build
  - master

stages:
  - stage: compile
    jobs: 
      - job: aspnet
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: 
              dotnet build 3_devops/devops.sln