FROM mcr.microsoft.com/dotnet/core/sdk as build
WORKDIR /aspnet
COPY . . 
RUN dotnet build
RUN dotnet publish --no-restore -c Release -o dist

FROM mcr.microsoft.com/dotnet/core/aspnet
WORKDIR /dist
# ENV ASPNETCORE_URLS=http://*:5000
COPY --from=build /aspnet/out .
# RUN ls -a
# RUN pwd
CMD ["dotnet", "Devops.Client.dll"]
